########
### API ####
#########

######## Lyric
### Request for a lyric
POST http://localhost:3000/api/v1/garmony/lyric
Content-Type: application/json

{
    "prompt": "Banana title"
}

### Retrieve all lyrics
GET http://localhost:3000/api/v1/garmony/lyric

### Retrieve one lyric
GET http://localhost:3000/api/v1/garmony/lyric/1

### Update a lyric
PUT http://localhost:3000/api/v1/garmony/lyric/1
Content-Type: application/json

{
  "title": "tile",
  "lyric": "change lyric",
  "cover": "cover",
  "speech": "speech"
}

###
DELETE http://localhost:3000/api/v1/garmony/lyric/2
